config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:show, :new, :create, :edit, :update] do
      resources :doses, only: [:new, :create, :destroy]
  end

  root to: "cocktails#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :doses
  has_many :cocktails, through: :doses
  before_destroy :check
  def check
    if doses.count > 0
      return false
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :set_cocktail, only: [:show, :edit, :update]
  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to root_path
  end

  def show
    @ingredients = Ingredient.all
    @dose = Dose.new
  end

  private
  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  before_action :set_cocktail

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private
  def set_cocktail
     @cocktail = Cocktail.find(params[:cocktail_id])
  end
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <br><br><br>
      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name, class: "form-control"%>
        <%= f.input :description, class: "form-control"%>
        <%= f.input :photo, class: "form-control"%>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/edit.html.erb
<%= render 'form' %>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://gq-images.condecdn.net/image/PRMLDAZqMAE/crop/1620/f/non-alcoholic-cocktails-GQ-23Jan18_istock_b.jpg');">
  <div class="banner-content">
    <h1>Simple Cocktails</h1><br>
    <p>
      <span id="banner-typed-text"></span>
    </p>
  </div>
</div>
<div class="wrpper">
  <div class="container">
  <h1>List of cocktails</h1>
    <div class="row">
    <% @cocktails.order('name').each do |cocktail| %>
      <div class="col-xs-12 col-md-4">
        <%= link_to cocktail_path(cocktail) do  %>
        <div class="image" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.2) 0%, rgba(0,36,61,0.2) 50%), url('<%= cl_image_path cocktail.photo unless cocktail.photo.blank? %>')" >
          <h3><%=cocktail.name%></h3>
        </div>
        <% end %>
      </div>
    <% end %>
    </div>
  </div>
 </div>

app/views/cocktails/new.html.erb
<%= render 'form' %>

app/views/cocktails/show.html.erb
<div class="show-wrapper" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.2) 0%, rgba(0,36,61,0.2) 50%), url('<%= cl_image_path @cocktail.photo unless @cocktail.photo.blank? %>')">
  <h1><%= @cocktail.name %></h1>
</div>
<div class="content">
  <div class="left">
    <h3>Description</h3>
    <p><%= @cocktail.description %></p><br>
    <%= link_to "Edit cocktail", edit_cocktail_path(@cocktail), class: "btn btn-primary" %>
  </div>
  <div class="right">
    <h3>Ingredients</h3>
    <ul>
      <% @cocktail.doses.each do |dose| %>
      <li><p><strong><%= @ingredients.find(dose.ingredient_id).name %></strong>&ensp;-&ensp;<%= dose.description %>&ensp;(<%= link_to "delete", cocktail_dose_path(@cocktail, dose), method: :delete %>)</p>
      </li>
      <% end %>
    </ul><br>
    <%= link_to "Add a ingredient", new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <br><br><br>
        <%= simple_form_for [@cocktail, @dose] do |t| %>
        <%= t.association :ingredient, collection: Ingredient.order('name'), class: "form-control js-basic-single" %>
        <%= t.input :description, class: "form-control" %>
        <%= t.submit class: "btn btn-primary" %>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <%= link_to "Simple Cocktails", root_path, class: "home"%>
  <%= link_to "Add Cocktail", new_cocktail_path, class: "btn btn-outline-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= yield %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application' %>
  </body>
</html>